### ISSUE TITLE
Percentages from all nodes vs. tagged nodes.

### ISSUE THREAD

**Issue by joto** [taginfo/taginfo#145]
Some statistics count all nodes, some count only tagged nodes. This can be confusing.

**Comment by georg-d** [comment]
Do you refer to ther % shown on the wiki page (e.g. https://wiki.openstreetmap.org/wiki/Tag:route%3Dpiste) and in "taginfo itself" (e.g. https://taginfo.openstreetmap.org/tags/route=piste#overview) which differ massively? 
![taginfo in wiki vs pure](https://user-images.githubusercontent.com/45993293/106325046-77c71500-627a-11eb-922f-f3ba03194a15.png)

**Comment by ZeLonewolf** [comment]
I should note that I've been working on a [rewrite of the taginfo template](https://wiki.openstreetmap.org/wiki/Template:Taginfo2) on the OSM wiki.  It's nearly complete and we're getting ready to deploy it as a replacement for {{taginfo}}.  I've written it to replicate the behavior of the existing taginfo box which shows the percentage of that specific value as compared to usages of that specific key (e.g. highway=residential is 29% of all highway=* keys).  As far as I know, there is no single API that provides the percentages in the way that the current wiki taginfo box reports them (the API reports percentages in the way taginfo reports), and so I make two calls.

I've not specifically asked for a new API call to provide both the counts and key-based percentages because it works with the existing API (two calls) and I don't want to make unnecessary work for people just for my convenience.  But if there is a desire to change the percentage to reflect per-key versus global percentages, and that results in a new API call being added, I would change the new taginfo box to use it.

**Comment by georg-d** [comment]
@ZeLonewolf  Do I understand correctly that the rewritten taginfo template will display the same percentage as the old, i.e. the difference between wiki's embedded taginfo and native taginfo will remain?

**Comment by ZeLonewolf** [comment]
Yes, that's correct - the intent is to switch to AJAX which fixes a bunch of formatting problems with the existing iframe version and allows us to customize it for different applications.

**Comment by joto** [comment]
Grmpf. The original issue here was about something totally different. And there already was an issue #309 about the new taginfo template stuff you are talking about. Please do not use this issue tracker as a general tool for discussing wiki-related stuff. I'd be happy to discuss changes to the taginfo API to make it more useful for you, but please open a new issue for each new, well, issue. Thanks.

**Comment by georg-d** [comment]
Dear @joto, do you think it's really appropriate to be angry and close the the original issue wihout being fixed? :-) It was described very briefly so that I was unsure _what exactly_ it targets and whether my observation would be the same (once the statsistic seems to divide by count of all objects and once only by the ones tagged with that key) that I prefered to _ask whether it's the same issue_ instead of instantly creating a dublicate. Now that I know you mean something else (I still don't know what) I created https://github.com/taginfo/taginfo/issues/315
