### ISSUE TITLE
Show status field from wiki

### ISSUE THREAD

**Issue by nebulon42** [taginfo/taginfo#196]
It would be great if taginfo could also show the status field from the info box at the wiki. Especially useful in case of `deprecated` tags. Maybe also not all values need to be shown only selected ones.

**Comment by nebulon42** [comment]
If I interpret https://github.com/taginfo/taginfo/blob/master/sources/wiki/get_wiki_data.rb#L357 correctly then the status is already parsed and only needs displaying.

**Comment by joto** [comment]
It is not displayed on purpose. The status is confusing and questionable.

**Comment by nebulon42** [comment]
Agreed, but it would be valuable to see if tags are discouraged to use. Would this be in the scope of this project?

**Comment by mboeringa** [comment]
> Agreed, but it would be valuable to see if tags are discouraged to use. Would this be in the scope of this project?

I was just about to open a new issue here, but I think I can simply reference a ticket I first opened on the iD issue tracker and that @bhousel commented on as related to TagInfo, because it seems very similar to the problem @nebulon42 raises here:

**iD should not suggest re-directed (incorrect) tags from Wiki:**
https://github.com/openstreetmap/iD/issues/4051

I agree with @nebulon42, TagInfo should not return deprecated and re-directed keys to other applications like iD. In the above linked example, you can see iD suggesting a false **tourism=tourism-attraction** key, while the TagInfo service links to a Wiki page with re-direction to the correct **tourism=attraction**.

Since TagInfo presents the false key as a proper one to other applications, editors like iD that depend on it, will pick these up, as @bhousel commented. 

It would be great if TagInfo somehow allowed for a clean requests without these deprecated and re-directed tags. This will prevent users from starting to re-use deprecated keys.

**Comment by joto** [comment]
First, taginfo does not "presents the false key as a proper one to other applications". Taginfo doesn't decide what's wrong and what's right. Applications using taginfo data should not expect taginfo to present only some kind of vetted information.

Second: Stop putting redirects into the Wiki, it is a poor way of declaring something to be deprecated.

Third: Don't put this on taginfo. If there is a sensible way of declaring something deprecated, taginfo will use it. Changing a wiki page after a poll with ten participants is not a sensible way of deciding anything. Until there is some better mechanism we will not make any progress here.

**Comment by mboeringa** [comment]
> First, taginfo does not "presents the false key as a proper one to other applications". Taginfo doesn't decide what's wrong and what's right. Applications using taginfo data should not expect taginfo to present only some kind of vetted information.

I guess my wording was incorrect. Yes, I understand the particular issue maybe insolvable from the TagInfo side, and I do appreciate and understand you want to keep TagInfo "tag neutral". You have some strong points here.

On the other hand, almost all editors use some kind of "generally accepted default tags". Without these, we couldn't even have symbolized nodes/ways and relations in editors at all, or rendered maps for that matter.

So I am just not sure if I entirely agree with your second point. If a new tag is not generally accepted, and has an alternative with a well documented Wiki page and long established usage, than I think a Wiki re-direct is fair (note: I actually haven't edited the OSM Wiki myself up to now, only participated in a few Wiki discussions). 

The case, as you also suggest, is probably different for "deprecated" old keys, that may have had long and well established usage and for which a re-direct is probably inappropriate. 

I guess this is a marked difference between the particular tag I used as example (a new tag **tourism=tourism-attraction** instead of well established **tourism=attraction**) versus a well established tagging being potentially replaced by another tagging scheme (e.g. **highway=bus_stop** and **public_transport=stop_postion + bus=yes**)

Anyway, your remark highlights that editors maybe should not use TagInfo directly for tag suggestions, as iD apparently does.

Whether we want to keep tagging as neutral as possible or not, it is likely that suggesting any tags based on low and potentially not generally accepted tagging schemes, may lead to a lot of usage that will in the long term hamper using the data.

Anyway, this is getting off topic for here.
