### ISSUE TITLE
Two tiny problems

### ISSUE THREAD

**Issue by iriman** [taginfo/taginfo#233]
I saw two problems while translating:
* Maybe a typo? "though"? "through"? In the following string:
This data is provided by the project for taginfo though the 'JSON project file' linked from above. See the wiki for a format description.
* Horizantal axis of histogram chart on
https://taginfo.openstreetmap.org/reports/key_lengths#histogram
is not visible and needs we make the page full-screen. Tested on Chrome Version 63.0.3239.132 (Official Build) (32-bit)

**Comment by joto** [comment]
I have fixed the first. The second problem is probably just due to the small screen size. I have sort-of fixed this now, but it is not perfect. But a good solution would be too much effort for the moment.

Next time please open a new issue for each problem, even if it is very small. This makes it easier to track.
