### ISSUE TITLE
Incorrectly working for tags where values are not english

### ISSUE THREAD

**Issue by Semigradsky** [taginfo/taginfo#239]
Example:
https://taginfo.openstreetmap.org/tags/genus%3Aru=Тополь

![screenshot from 2018-07-12 18-15-46](https://user-images.githubusercontent.com/1198848/42642498-a7847ecc-85ff-11e8-9cf4-d75a13f19b01.png)

**Comment by joto** [comment]
Might be related to #235.

**Comment by matkoniecz** [comment]
Also for keys - https://taginfo.openstreetmap.org/keys/millennium%3Aus%C5%82ugi#map

note that generated overpass turbo query is broken

**Comment by iriman** [comment]
Also occurs in overpass-turbo queries. for example query [on this page](https://taginfo.openstreetmap.org/tags/name=%D8%B1%D8%A7%D9%87%D8%AF%D8%A7%D8%B1%D8%AE%D8%A7%D9%86%D9%87#map).

![untitled](https://user-images.githubusercontent.com/8467903/43329622-23651628-91d6-11e8-9215-f9bf1a3f6fde.png)

**Comment by joto** [comment]
Investigated this: This is definitely not a problem in taginfo code but in Sinatra or somewhere else in the ruby libs. If you use the alternative URL form https://taginfo.openstreetmap.org/tags/?key=genus%3Aru&value=%D0%A2%D0%BE%D0%BF%D0%BE%D0%BB%D1%8C it works.

Might be related to #235 but is the inverse problem: Instead of not decoding the URL it seems to reencode it. Unfortunately this is hard to test without a test system.

**Comment by joto** [comment]
I hacked the fix https://github.com/sinatra/sinatra/commit/529f79125eaa9a57a3cea3898de3155c6ad1dd90 mentioned in #235 into the code currently running on the taginfo server (by editing `/var/lib/gems/2.5.0/gems/sinatra-2.0.3/lib/sinatra/base.rb`) and it fixed the problem. The fix should be in the next released version of sinatra but until then I am not sure what to do.

@tomhughes any suggestions?

**Comment by matkoniecz** [comment]
> The fix should be in the next released version of sinatra but until then I am not sure what to do.

How often sinatra releases new versions? This bug may wait a week or month, it is nothing critical.

**Comment by ImreSamu** [comment]
Sinatra 2.0.4 release: https://github.com/sinatra/sinatra/releases/tag/v2.0.4
