### ISSUE TITLE
Some missing translations

### ISSUE THREAD

**Issue by iriman** [taginfo/taginfo#241]
Missing:
* https://taginfo.openstreetmap.org/search?q=service#fulltext  (text in red)
* Section INTERNATIONAL in main page: https://taginfo.openstreetmap.org
* Section "about this website" in about page: https://taginfo.openstreetmap.org/about

Either missing translation or need correcting alignment for rtl:
* https://taginfo.openstreetmap.org/taginfo and linked pages

**Comment by joto** [comment]
Yeah, some parts of taginfo can not be translated, because they are either mostly for internal developer use (everything under `taginfo`) or where the texts are expected to change for each taginfo site (international/about) which makes them more difficult to translate. Not ideal maybe, but harder to change.

And yes, I should fix the alignment in the `taginfo/` pages.

**Comment by joto** [comment]
The `taginfo/` pages are fixed and I added the info about the non-translatable pages to the wiki at https://wiki.openstreetmap.org/wiki/Taginfo/I18N .
