### ISSUE TITLE
Writing Farsi in native language

### ISSUE THREAD

**Issue by iriman** [taginfo/taginfo#242]
In this page https://taginfo.openstreetmap.org/taginfo/i18n?lang=fa native name of Farsi is written 'فارْسِی'.

Although Arabic and Farsi are very similar in letters, but they are far different languages. The usage of diacritics in Farsi is only when there's a possibility of wrong pronunciation, so 'فارسی' is correct and 'فارْسِی' isn't. Btw the latter may mislead to a bad pronunciation: /far-say/, while /far-see/ is correct.

thanks :)

![untitled](https://user-images.githubusercontent.com/8467903/42897716-14979b18-8ad6-11e8-9899-ab50ba9d5b8a.png)

**Comment by joto** [comment]
The reason this is different is that this text comes from here: https://github.com/ai/r18n/blob/master/r18n-core/locales/fa.rb#L8 instead of our own list of language names. You should open an issue on that repository, too.

I am leaving this open here, because it might make sense to use our own language name here for consistency, but it might take a bit for me to implement this.

**Comment by iriman** [comment]
thank you. It's now fixed there: https://github.com/ai/r18n/issues/179
