### ISSUE TITLE
Show relations on "Geographical distribution of this tag" map

### ISSUE THREAD

**Issue by jeisenbe** [taginfo/taginfo#274]
It appears that relations are not currently shown on the taginfo "Geographical distribution of this tag" tab map. 

For example, [route=power](https://taginfo.openstreetmap.org/tags/route=power#map
) shows only about 6 squares on the map:

<img width="690" alt="Map of route=power distribution" src="https://user-images.githubusercontent.com/42757252/72206121-79863500-34cd-11ea-809b-f6d57d39e976.png">

But [searching overpass-turbo](http://overpass-turbo.eu/s/PFb) makes it clear that there are many more areas with features

Would it be feasible to find the center of a relation's bounding box (similar to the function of `out center` in overpass) and use this for the map, to avoid showing too few places for tags used only on relations?

**Comment by joto** [comment]
There are several problems with showing the relations on the map. First it is unclear how to show the location at all, because the location of a relation is not well defined, showing the bbox can be quite misleading, for instance the bounding box of the boundary of the US would be half the planet. I fear that adding something like this would lead to more questions and misunderstandings. And then there is the added overhead of getting to that location, something I am very reluctant to do in the taginfo code.

Maybe this is something which could be tested outside of taginfo first to see how this would look and we can then see whether and how this could be integrated.

**Comment by jeisenbe** [comment]
> for instance the bounding box of the boundary of the US would be half the planet.

boundary=administrative features would be the only common relation
type which would show this problem. 99% of relation bounding boxes
would fit in a single "pixel" on the map.

Perhaps features with large bounding boxes could be discarded?

> there is the added overhead of getting to that location, something I am very reluctant to do in the taginfo code

I was worried it might be too expensive in regards to server resources.

If it proves to be infeasible, perhaps the text can be edited from
"Geographical distribution of this tag" to "Geographical distribution
of ways and nodes with this tag" - this would help users know that
relations are not represented.
