### ISSUE TITLE
Percentages differ between embed API and other API calls

### ISSUE THREAD

**Issue by ZeLonewolf** [taginfo/taginfo#308]
I'm using water=reservoir as the example, but this appears to be happening across the board.

Consider:
https://taginfo.openstreetmap.org/embed/tag?key=water&value=reservoir

This reports 1,240 nodes out of 9,088 total on the water=* key (13.64%), which appears to be the correct results.

However, when I visit the web interface (https://taginfo.openstreetmap.org/tags/?key=water&value=reservoir) I see:
1,240 nodes (0.00%)
The API reports the same value of 0 for water=reservoir nodes:
https://taginfo.openstreetmap.org/api/4/tag/stats?key=water&value=reservoir

**Comment by 1ec5** [comment]
Other than for this issue, the user script at https://wiki.openstreetmap.org/wiki/User:ZeLonewolf/taginfo.js could be installed on the wiki as a dynamic replacement for the current taginfo extension’s tag statistics box (with the existing box as a fallback for browsers without JavaScript). The user script gives us some opportunities to better integrate the data with the page stylistically, which isn’t possible with the iframe due to cross-site scripting restrictions.

**Comment by joto** [comment]
Those are different numbers. https://taginfo.openstreetmap.org/tags/?key=water&value=reservoir reports the percentage of **all** objects in the database with the tag `water=reservoir`. https://taginfo.openstreetmap.org/embed/tag?key=water&value=reservoir reports the number of objects with tag `water=reservoir` relative to the number of objects with tag key `water`. So this is not wrong, just might be confusing. The embed-pages have a title text that appears when you hover the mouse over them that says what the number is supposed to mean, but it isn't really a great text. It is difficult to explain these kinds of things in few words.

**Comment by ZeLonewolf** [comment]
Thanks for clarifying this.  I'll just implement this with two separate calls to the taginfo, one to grab the tag counts and a separate one to grab the key counts.
