### ISSUE TITLE
Add "Examples" tab

### ISSUE THREAD

**Issue by jidanni** [taginfo/taginfo#348]
On https://taginfo.openstreetmap.org/tags/?key=amenity&value=waste_dump_site#overview
there is
"Overview Combinations Chronology Map Wiki Projects Characters"

Please also add "Examples",
so the user can actually see the tag in use on the map.

**Comment by jidanni** [comment]
The Examples would simply be a list
1.
2.
3...
of places where the tag appears on the map, perhaps initially sorted by time, latest first, but also via clicking, sorted by size, etc.

Each page could handle 50 items, etc.

**Comment by jidanni** [comment]
Sure, you could say that it what the Overpass Turbo link is for. But still adding an Examples tab would save messing with a bounding box, etc.

**Comment by joto** [comment]
I agree that this could be a useful feature. But this would mean that we have to

a) actually know where a tag is being used (which taginfo doesn't care about because it adds a lot of (so far) unnecessary data which means the taginfo server would need more resources)
b) know how tags are rendered (doesn't make any sense showing examples where you can't see anything)
c) know how combinations of tags are rendered (which is even more difficult than b)
d) know b) and c) not only for the "standard" map, but also for other rendering styles,
e) decide somehow on "good examples" that are more helpful than not (what if a tag is used in the wrong way in one of those examples, then taginfo could be seen to promote the wrong tagging).

Because of all of this I think the idea isn't something we can actually do in practice unfortunately. If there is a curated list of examples, that would be something we could include through the "projects" feature of taginfo.

**Comment by jidanni** [comment]
All I know is currently the user goes to the Map page,
and finds that the Map page knows where the goods are,
but is not forthcoming any further.

**Comment by jidanni** [comment]
> b) know how tags are rendered (doesn't make any sense showing examples where you can't see anything)

Ah, but maybe the user is trying to confirm that the tag isn't being rendered.

So if and how the tag is being rendered is not something you should be worried about.

**Comment by jidanni** [comment]
> d) know b) and c) not only for the "standard" map, but also for other rendering styles,

It is just your job to let the user get to some way or node on OSM.ORG/ . He can then click the layers he wants to see.

**Comment by jidanni** [comment]
> e) decide somehow on "good examples" that are more helpful than not (what if a tag is used in the wrong way in one of those examples, then taginfo could be seen to promote the wrong tagging).

OK, then don't call it Examples. Call it List.
And then let him click on if he wants it sorted by date (way or node number) or size (area) etc.

**Comment by jidanni** [comment]
Another idea would just be have a second link to Overpass Turbo, but with an initial bounding box of world wide.

**Comment by joto** [comment]
As I said, this isn't something we can really do. Sorry.
