### ISSUE TITLE
Allow surface= search to work as a filter

### ISSUE THREAD

**Issue by matkoniecz** [taginfo/taginfo#372]
Tested on https://taginfo.openstreetmap.org/projects/streetcomplete#tags

`surface` works, `surface=` fails (gives no matches)

BTW, is there way to filter and get only `^surface$=*` matches?

**Comment by joto** [comment]
That search is a substring search on the key and value fields, not together but separately. That's why the `=` in the search string doesn't work here and probably never will. And no, there is no regex search. The search is designed for rough ad-hoc searches, not for superspecific special searches. Download the sqlite files for that and you can use all the SQL magic you need.

**Comment by matkoniecz** [comment]
I hoped that "show all values of `surface` key used by a project" via filtering in menu there qualifies as ad-hoc search.

Though it can be actually done via https://taginfo.openstreetmap.org/keys/surface#projects
