### ISSUE TITLE
Search: Allow searching a key/value/namespace directly from the list

### ISSUE THREAD

**Issue by danieldegroot2** [taginfo/taginfo#389]
At least partially a wishlist item;

Allow users to search a key/value(/prefix/suffix/infix) directly from the list using a hotkey.

Ex. I find some value ("tower") which interests me. Using the hotkey will bring me to `search?q=tower`.
![image](https://user-images.githubusercontent.com/67521919/210183206-b9af2153-e59c-4aee-910d-74a77ec91b3b.png)

Sidenote: on individual entries, users can already see [similar keys](https://taginfo.openstreetmap.org/keys/pump#similar)

(similar could be done for words in project usage descriptions, but this would be more complicated and it's understandable this isn't going to be a feature anytime soon.)

**Comment by joto** [comment]
You can use your browser for that. Taginfo supports the "opensearch" API, so you can define taginfo as default search engine in your browser and then highlight the word and use the right-click menu to search for that word in taginfo. At least this is how it works in Firefox, other browsers are probaby similar. I admit it is a bit complicated though because it only works when taginfo is your default search engine.

Anyway, this seems to be too exotic to me. Most users will never even figure out that something like that would be possible. So no, I am not going to implement that.

**Comment by danieldegroot2** [comment]
Thanks. No problem.
