### ISSUE TITLE
Problem to view taginfo.openstreetmap.org with Palemoon browser

### ISSUE THREAD

**Issue by damjang** [taginfo/taginfo#394]
With my Palemoon browser ( http://www.palemoon.org/ ) there are problems viewing taginfo pages. I see a javascript error with class list problem. I write to the forum of palemoon and the author respond:
 `They are trying to use the public class field syntax which we don't support.`

Please see the whole response here: https://forum.palemoon.org/viewtopic.php?f=70&t=29279

Can be possible to correct this? Thank you!

**Comment by joto** [comment]
Public class fields are supported by all major browsers and have for a while and they are in the ECMA standard. Hardly a "latest toy gets pushed into Chrome".

That being said I am not totally against supporting older browsers as long as the code doesn't become too ugly. Traditionally taginfo has been using a very simple and outdated Javascript style and I have been slowly trying to bring this in line with what a modern developer would expect. I already had to roll back private fields in c1664efe5566dae67136627fad2a6bcac8ceed5e, because this didn't work everywhere. Maybe you can provide a PR and then we can see how easy it would be to support palemoon.

**Comment by damjang** [comment]
Thank you for checking this. But I'm not a programmer and I'm not able to do a PR, sorry (I use github just to do some language/translation projects).
